export const lorem = [
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Etiam dignissim diam quis enim lobortis scelerisque. Vitae justo eget magna fermentum iaculis eu non. Egestas maecenas pharetra convallis posuere. Magna ac placerat vestibulum lectus. Congue quisque egestas diam in arcu cursus. Urna condimentum mattis pellentesque id nibh tortor. Tortor at auctor urna nunc id cursus metus aliquam. Id porta nibh venenatis cras sed felis. Massa vitae tortor condimentum lacinia quis vel eros. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Quisque non tellus orci ac auctor. Orci a scelerisque purus semper eget duis at. Leo duis ut diam quam nulla porttitor massa. Sed nisi lacus sed viverra.',

'Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Id leo in vitae turpis massa sed elementum. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Risus in hendrerit gravida rutrum quisque. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Nibh tellus molestie nunc non blandit massa enim nec. Purus in massa tempor nec feugiat. Elementum pulvinar etiam non quam lacus. A lacus vestibulum sed arcu non odio euismod lacinia. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Velit egestas dui id ornare arcu odio ut. Turpis nunc eget lorem dolor sed viverra ipsum.',

'Convallis tellus id interdum velit laoreet. Commodo elit at imperdiet dui. Tristique magna sit amet purus gravida quis blandit. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Porta nibh venenatis cras sed felis eget velit. Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Morbi quis commodo odio aenean sed. Arcu odio ut sem nulla pharetra diam sit. Leo integer malesuada nunc vel risus commodo viverra. Sed felis eget velit aliquet sagittis id consectetur. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Et netus et malesuada fames ac turpis egestas integer eget. Velit laoreet id donec ultrices tincidunt arcu. Egestas sed tempus urna et pharetra pharetra massa.',

'Tristique senectus et netus et malesuada. Sit amet consectetur adipiscing elit duis. Vitae elementum curabitur vitae nunc sed velit. Lectus magna fringilla urna porttitor rhoncus. Malesuada bibendum arcu vitae elementum curabitur. Porttitor lacus luctus accumsan tortor posuere ac. Nisi vitae suscipit tellus mauris a. At augue eget arcu dictum varius duis at consectetur lorem. Faucibus scelerisque eleifend donec pretium. Et netus et malesuada fames ac turpis egestas.',

'Pulvinar mattis nunc sed blandit. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Aenean pharetra magna ac placerat. Quam lacus suspendisse faucibus interdum. Consequat ac felis donec et. Nisi quis eleifend quam adipiscing vitae proin. Cursus turpis massa tincidunt dui ut. Cras pulvinar mattis nunc sed blandit. Ipsum consequat nisl vel pretium lectus. Ornare arcu dui vivamus arcu felis bibendum. Diam maecenas sed enim ut. Ultrices eros in cursus turpis massa. Tincidunt vitae semper quis lectus nulla at volutpat diam ut.',
]